[package]
name = "resolver"
version = "0.1.0"
edition = "2021"


[dependencies]
frontend = { path = "../frontend" }
tools = { path = "../tools" }
thiserror = { workspace = true }
colored = { workspace = true }
ecow = { workspace = true }