[package]
name = "runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
frontend = { path = "../frontend" }
tools = { path = "../tools" }
resolver = { path = "../resolver" }
colored = { workspace = true }
ecow = { workspace = true }
thiserror = { workspace = true }
